### ISSUE TITLE
[sprint] sprint 2 backlog

### ISSUE THREAD

**Issue by ray017** [swsnu/swpp2020-team2#2]
Please comment on what you have done in sprint 2.
Comments will be integrated into sprint 2 backlog and will be submitted to TAs.

**Comment by ray017** [comment]
wrote fields and methods for frontend components, subcomponents, and services.
made class diagrams for frontend by online class diagram tool, visual-paradigm online.
contributed to frontend images in the Design and planning document in Github WIki.

**Comment by ariadne240** [comment]
In Github Wiki, I wrote System Architecture and Design Details (Model and View part).
I made skeleton codes for frontend (React) and backend (Django), and pushed it to the repository.

**Comment by sdm1230** [comment]
Wrote Frontend Algorithms descriptions of Wiki : Design and Planning
- descriptions of components method
- descriptions of subcomponents method
- descriptions of services method
For writing these, made up and added the parameters corresponding to each of functions.
Changing the parameter's property: string --> int 
 ex) university:string --> universityId : number

**Comment by taekop** [comment]
What I wrote in design and planning document
 - Controller in design details
 - background RESTful API, django model
 - Implementation plan and testing plan
