### ISSUE TITLE
sprint3 Question list

### ISSUE THREAD

**Issue by sdm1230** [swsnu/swpp2020-team2#29]

**Comment by sdm1230** [comment]
1. 전체 필터링할 때 프론트에서 filter method로 하나하나 해주나 아니면 백엔드 api 에서 다뤄주나? 일반적으로?

**Comment by ray017** [comment]
왜 나만 csrf cookie 에러나요

**Comment by ariadne240** [comment]
Closing issue since now sprint 3 done
