### ISSUE TITLE
Coveralls 설정 관련

### ISSUE THREAD

**Issue by hy00nc** [swsnu/swpp2020-team2#31]
안녕하세요, 확인해보니 frontend test가 정상적으로 종료되지 않아서 coveralls에 결과가 포함되지 않는 것 같습니다.

Travis 빌드 로그 확인하셔서 Testing 이슈 해결하시면 coveralls에 제대로 반영 될 것 같습니다.

**Comment by ariadne240** [comment]
Checked.
